name: Labeler
on:
  pull_request_target:
  issues:
    types: [opened, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: List contents of .github directory
      run: ls -la .github
    - name: Cat labeler.yml
      run: cat .github/labeler.yml
    - uses: actions/labeler@v4
      if: github.event_name == 'pull_request_target'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@v3
    - name: List contents of .github directory
      run: ls -la .github
    - name: Cat issue-labeler.yml
      run: cat .github/issue-labeler.yml
    - name: Debug event
      env:
        EVENT_CONTEXT: ${{ toJson(github.event) }}
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Event context: $EVENT_CONTEXT"
    - uses: github/issue-labeler@v2
      if: github.event_name == 'issues'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/issue-labeler.yml
        enable-versioned-regex: 0
