name: Labeler
on:
  pull_request_target:
  issues:
    types: [opened, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: List contents of .github directory
      run: ls -la .github
    - name: Cat labeler.yml
      run: cat .github/labeler.yml
    - uses: actions/labeler@v4.0.0
      if: github.event_name == 'pull_request_target'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/labeler@v4.0.0
      if: github.event_name == 'issues'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/issue-labeler.yml
