name: Labeler
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: List contents of .github directory
      run: ls -la .github
    - name: Cat labeler.yml
      run: cat .github/labeler.yml
    - uses: actions/labeler@v4.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
